// Date: 3/17/2013 11:03:03 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package MHF.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelBullfango extends ModelBase
{
  //fields
    ModelRenderer tusk1;
    ModelRenderer tusk2;
    ModelRenderer basetusk1;
    ModelRenderer basetusk2;
    ModelRenderer snout;
    ModelRenderer head;
    ModelRenderer frontMane;
    ModelRenderer body;
    ModelRenderer mane1;
    ModelRenderer mane2;
    ModelRenderer mane3;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer theigh1;
    ModelRenderer theigh2;
    ModelRenderer theigh3;
    ModelRenderer theigh4;
  
  public ModelBullfango()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      tusk1 = new ModelRenderer(this, 0, 9);
      tusk1.addBox(-0.2F, 12F, -19F, 1, 1, 7);
      tusk1.setRotationPoint(2F, 7F, -7F);
      tusk1.setTextureSize(128, 64);
      tusk1.mirror = true;
      setRotation(tusk1, -0.3316126F, 0.3839724F, 0F);
      tusk2 = new ModelRenderer(this, 0, 9);
      tusk2.addBox(0F, 12F, -19F, 1, 1, 7);
      tusk2.setRotationPoint(2F, 7F, -7F);
      tusk2.setTextureSize(128, 64);
      tusk2.mirror = true;
      setRotation(tusk2, -0.3316126F, -0.3316126F, 0F);
      basetusk1 = new ModelRenderer(this, 0, 0);
      basetusk1.addBox(-1F, 5F, -17F, 2, 2, 7);
      basetusk1.setRotationPoint(2F, 7F, -7F);
      basetusk1.setTextureSize(128, 64);
      basetusk1.mirror = true;
      setRotation(basetusk1, 0.1047198F, 0.3839724F, 0F);
      basetusk2 = new ModelRenderer(this, 0, 0);
      basetusk2.addBox(-1F, 5F, -17F, 2, 2, 7);
      basetusk2.setRotationPoint(2F, 7F, -7F);
      basetusk2.setTextureSize(128, 64);
      basetusk2.mirror = true;
      setRotation(basetusk2, 0.1047198F, -0.3839724F, 0F);
      snout = new ModelRenderer(this, 52, 0);
      snout.addBox(-3.5F, 2F, -14F, 7, 6, 7);
      snout.setRotationPoint(2F, 7F, -7F);
      snout.setTextureSize(128, 64);
      snout.mirror = true;
      setRotation(snout, 0.1047198F, 0F, 0F);
      head = new ModelRenderer(this, 74, 0);
      head.addBox(-6.5F, -6F, -10F, 13, 14, 14);
      head.setRotationPoint(2F, 7F, -7F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0.1745329F, 0F, 0F);
      frontMane = new ModelRenderer(this, 106, 19);
      frontMane.addBox(0F, -11F, -5F, 0, 6, 11);
      frontMane.setRotationPoint(2F, 7F, -7F);
      frontMane.setTextureSize(128, 64);
      frontMane.mirror = true;
      setRotation(frontMane, 0.1745329F, 0F, 0F);
      body = new ModelRenderer(this, 0, 0);
      body.addBox(-7.5F, -7F, 0F, 15, 14, 22);
      body.setRotationPoint(2F, 7F, -7F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, -0.1047198F, 0F, 0F);
      mane1 = new ModelRenderer(this, 74, 15);
      mane1.addBox(0F, 0F, 0F, 0, 6, 15);
      mane1.setRotationPoint(-1F, -5F, -4F);
      mane1.setTextureSize(128, 64);
      mane1.mirror = true;
      setRotation(mane1, -0.1047198F, 0F, 0F);
      mane2 = new ModelRenderer(this, 98, 21);
      mane2.addBox(0F, 0F, 0F, 0, 6, 15);
      mane2.setRotationPoint(2F, -5F, 0F);
      mane2.setTextureSize(128, 64);
      mane2.mirror = true;
      setRotation(mane2, -0.1047198F, 0F, 0F);
      mane3 = new ModelRenderer(this, 74, 15);
      mane3.addBox(0F, 0F, 0F, 0, 6, 15);
      mane3.setRotationPoint(5F, -5F, -4F);
      mane3.setTextureSize(128, 64);
      mane3.mirror = true;
      setRotation(mane3, -0.1047198F, 0F, 0F);
      leg1 = new ModelRenderer(this, 22, 39);
      leg1.addBox(-2.5F, 0F, -2.5F, 5, 6, 5);
      leg1.setRotationPoint(-4F, 18F, 12F);
      leg1.setTextureSize(128, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 22, 39);
      leg2.addBox(-2.5F, 0F, -2.5F, 5, 6, 5);
      leg2.setRotationPoint(8F, 18F, 12F);
      leg2.setTextureSize(128, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 38);
      leg3.addBox(-2.5F, 0F, -2.5F, 5, 7, 5);
      leg3.setRotationPoint(-4F, 17F, -3F);
      leg3.setTextureSize(128, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 38);
      leg4.addBox(-2.5F, 0F, -2.5F, 5, 7, 5);
      leg4.setRotationPoint(8F, 17F, -3F);
      leg4.setTextureSize(128, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      theigh1 = new ModelRenderer(this, 24, 53);
      theigh1.addBox(-2.5F, 0F, -2.5F, 5, 5, 6);
      theigh1.setRotationPoint(-4F, 13F, 11F);
      theigh1.setTextureSize(128, 64);
      theigh1.mirror = true;
      setRotation(theigh1, 0F, 0F, 0F);
      theigh2 = new ModelRenderer(this, 24, 53);
      theigh2.addBox(-2.5F, 0F, -2.5F, 5, 5, 6);
      theigh2.setRotationPoint(8F, 13F, 11F);
      theigh2.setTextureSize(128, 64);
      theigh2.mirror = true;
      setRotation(theigh2, 0F, 0F, 0F);
      theigh3 = new ModelRenderer(this, 0, 51);
      theigh3.addBox(-2.5F, 0F, -2.5F, 5, 6, 7);
      theigh3.setRotationPoint(-4F, 11F, -3F);
      theigh3.setTextureSize(128, 64);
      theigh3.mirror = true;
      setRotation(theigh3, 0F, 0F, 0F);
      theigh4 = new ModelRenderer(this, 0, 51);
      theigh4.addBox(-2.5F, 0F, -2.5F, 5, 6, 7);
      theigh4.setRotationPoint(8F, 11F, -3F);
      theigh4.setTextureSize(128, 64);
      theigh4.mirror = true;
      setRotation(theigh4, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    tusk1.render(par7);
    tusk2.render(par7);
    basetusk1.render(par7);
    basetusk2.render(par7);
    snout.render(par7);
    head.render(par7);
    frontMane.render(par7);
    body.render(par7);
    mane1.render(par7);
    mane2.render(par7);
    mane3.render(par7);
    leg1.render(par7);
    leg2.render(par7);
    leg3.render(par7);
    leg4.render(par7);
    theigh1.render(par7);
    theigh2.render(par7);
    theigh3.render(par7);
    theigh4.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);   
    this.head.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.head.rotateAngleX = 0.2F * par5 / (180F / (float)Math.PI);
    this.snout.rotateAngleY = par4 / (180F / (float)Math.PI);
    this.snout.rotateAngleX = 0.2F * par5 / (180F / (float)Math.PI);
    this.leg1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
    this.theigh1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
    this.leg2.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
    this.theigh2.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
    this.leg3.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 1.4F * par2;
    this.leg4.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
    
    
    
  }

}
