// Date: 3/6/2013 11:02:02 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package MHF.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelFish extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer dorsal;
    ModelRenderer leftfin;
    ModelRenderer rightfin;
    ModelRenderer tail;
    ModelRenderer toptail;
    ModelRenderer bottomtail;
  
  public ModelFish()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      body = new ModelRenderer(this, 16, 0);
      body.addBox(-1F, -2F, -6F, 2, 4, 6);
      body.setRotationPoint(-1F, 21F, 2F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0.0174533F);
      dorsal = new ModelRenderer(this, 0, 0);
      dorsal.addBox(-0.5F, -3F, -5F, 1, 2, 4);
      dorsal.setRotationPoint(-1F, 21F, 2F);
      dorsal.setTextureSize(32, 32);
      dorsal.mirror = true;
      setRotation(dorsal, 0.2268928F, 0F, 0F);
      leftfin = new ModelRenderer(this, 0, 13);
      leftfin.addBox(1.5F, -1F, -4F, 1, 2, 2);
      leftfin.setRotationPoint(-1F, 21F, 2F);
      leftfin.setTextureSize(32, 32);
      leftfin.mirror = true;
      setRotation(leftfin, 0F, 0.3839724F, 0F);
      rightfin = new ModelRenderer(this, 0, 13);
      rightfin.addBox(-2.5F, -1F, -4F, 1, 2, 2);
      rightfin.setRotationPoint(-1F, 21F, 2F);
      rightfin.setTextureSize(32, 32);
      rightfin.mirror = true;
      setRotation(rightfin, 0F, -0.3839724F, 0F);
      tail = new ModelRenderer(this, 0, 6);
      tail.addBox(-0.5F, -1.5F, -1F, 1, 3, 4);
      tail.setRotationPoint(-1F, 21F, 2F);
      tail.setTextureSize(32, 32);
      tail.mirror = true;
      setRotation(tail, 0F, 0F, 0F);
      toptail = new ModelRenderer(this, 12, 0);
      toptail.addBox(0F, -1F, 2F, 0, 2, 2);
      toptail.setRotationPoint(-1F, 21F, 2F);
      toptail.setTextureSize(32, 32);
      toptail.mirror = true;
      setRotation(toptail, 0.2443461F, 0F, 0F);
      bottomtail = new ModelRenderer(this, 12, 0);
      bottomtail.addBox(0F, -1F, 2F, 0, 2, 2);
      bottomtail.setRotationPoint(-1F, 21F, 2F);
      bottomtail.setTextureSize(32, 32);
      bottomtail.mirror = true;
      setRotation(bottomtail, -0.2443461F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    body.render(par7);
    dorsal.render(par7);
    leftfin.render(par7);
    rightfin.render(par7);
    tail.render(par7);
    toptail.render(par7);
    bottomtail.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    this.tail.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.2F * par2;
    this.toptail.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.2F * par2;
    this.bottomtail.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.2F * par2;
  }

}
