// Date: 6/22/2013 12:40:18 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package MHF.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.client.model.ModelRenderer;

public class ModelRaptor extends ModelBase
{
  //fields
    ModelRenderer HeadCrest;
    ModelRenderer Head;
    ModelRenderer AMouth;
    ModelRenderer BMouth;
    ModelRenderer Nostril;
    ModelRenderer RTheigh;
    ModelRenderer RAnkle;
    ModelRenderer RFoot;
    ModelRenderer LTheigh;
    ModelRenderer LAnkle;
    ModelRenderer LFoot;
    ModelRenderer ATail;
    ModelRenderer BTail;
    ModelRenderer Neck;
    ModelRenderer Body;
    ModelRenderer RArm;
    ModelRenderer LArm;
    ModelRenderer LHand;
    ModelRenderer RHand;
  
  public ModelRaptor()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      HeadCrest = new ModelRenderer(this, 0, 0);
      HeadCrest.addBox(0F, -10F, -6F, 0, 5, 7);
      HeadCrest.setRotationPoint(2.5F, 4F, 8F);
      HeadCrest.setTextureSize(64, 32);
      HeadCrest.mirror = true;
      setRotation(HeadCrest, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(-2.5F, -7F, -8F, 5, 7, 8);
      Head.setRotationPoint(2.5F, 4F, 8F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      AMouth = new ModelRenderer(this, 0, 0);
      AMouth.addBox(-1.5F, -1F, -6F, 3, 1, 6);
      AMouth.setRotationPoint(2.5F, 1.5F, 0F);
      AMouth.setTextureSize(64, 32);
      AMouth.mirror = true;
      setRotation(AMouth, 0F, 0F, 0F);
      BMouth = new ModelRenderer(this, 0, 0);
      BMouth.addBox(-1.5F, 0F, -6F, 3, 1, 6);
      BMouth.setRotationPoint(2.5F, 1.5F, 0F);
      BMouth.setTextureSize(64, 32);
      BMouth.mirror = true;
      setRotation(BMouth, 0F, 0F, 0F);
      Nostril = new ModelRenderer(this, 0, 0);
      Nostril.addBox(0F, 0F, 0F, 2, 1, 4);
      Nostril.setRotationPoint(1.5F, -0.5F, -4F);
      Nostril.setTextureSize(64, 32);
      Nostril.mirror = true;
      setRotation(Nostril, 0F, 0F, 0F);
      RTheigh = new ModelRenderer(this, 0, 0);
      RTheigh.addBox(-4F, 0F, 0F, 4, 5, 8);
      RTheigh.setRotationPoint(1F, 8F, 18F);
      RTheigh.setTextureSize(64, 32);
      RTheigh.mirror = true;
      setRotation(RTheigh, -1.134464F, 0F, 0F);
      RAnkle = new ModelRenderer(this, 0, 0);
      RAnkle.addBox(-3.5F, 6F, 1F, 3, 9, 3);
      RAnkle.setRotationPoint(1F, 8F, 18F);
      RAnkle.setTextureSize(64, 32);
      RAnkle.mirror = true;
      setRotation(RAnkle, -0.3490659F, 0F, 0F);
      RFoot = new ModelRenderer(this, 0, 0);
      RFoot.addBox(0F, 0F, 0F, 4, 2, 5);
      RFoot.setRotationPoint(-3F, 22F, 12F);
      RFoot.setTextureSize(64, 32);
      RFoot.mirror = true;
      setRotation(RFoot, 0F, 0F, 0F);
      LTheigh = new ModelRenderer(this, 0, 0);
      LTheigh.addBox(0F, 0F, 0F, 4, 5, 8);
      LTheigh.setRotationPoint(4F, 8F, 18F);
      LTheigh.setTextureSize(64, 32);
      LTheigh.mirror = true;
      setRotation(LTheigh, -1.134464F, 0F, 0F);
      LAnkle = new ModelRenderer(this, 0, 0);
      LAnkle.addBox(0.5F, 6F, 1F, 3, 9, 3);
      LAnkle.setRotationPoint(4F, 8F, 18F);
      LAnkle.setTextureSize(64, 32);
      LAnkle.mirror = true;
      setRotation(LAnkle, -0.3490659F, 0F, 0F);
      LFoot = new ModelRenderer(this, 0, 0);
      LFoot.addBox(0F, 0F, 0F, 4, 2, 5);
      LFoot.setRotationPoint(4F, 22F, 12F);
      LFoot.setTextureSize(64, 32);
      LFoot.mirror = true;
      setRotation(LFoot, 0F, 0F, 0F);
      ATail = new ModelRenderer(this, 0, 0);
      ATail.addBox(-1.5F, -1.5F, 0F, 3, 3, 10);
      ATail.setRotationPoint(2.5F, 7.5F, 21F);
      ATail.setTextureSize(64, 32);
      ATail.mirror = true;
      setRotation(ATail, 0F, 0F, 0F);
      BTail = new ModelRenderer(this, 0, 0);
      BTail.addBox(-1F, -1F, 9F, 2, 2, 7);
      BTail.setRotationPoint(2.5F, 7.5F, 21F);
      BTail.setTextureSize(64, 32);
      BTail.mirror = true;
      setRotation(BTail, 0F, 0F, 0F);
      Neck = new ModelRenderer(this, 0, 0);
      Neck.addBox(-2F, -1F, -7F, 4, 4, 7);
      Neck.setRotationPoint(2.5F, 6F, 11F);
      Neck.setTextureSize(64, 32);
      Neck.mirror = true;
      setRotation(Neck, -0.715585F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 7, 8, 14);
      Body.setRotationPoint(-1F, 5F, 8F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      RArm = new ModelRenderer(this, 0, 0);
      RArm.addBox(0F, 0F, 0F, 3, 5, 3);
      RArm.setRotationPoint(-2F, 8F, 9F);
      RArm.setTextureSize(64, 32);
      RArm.mirror = true;
      setRotation(RArm, -0.5235988F, 0F, 0F);
      LArm = new ModelRenderer(this, 0, 0);
      LArm.addBox(0F, 0F, 0F, 3, 5, 3);
      LArm.setRotationPoint(4F, 8F, 9F);
      LArm.setTextureSize(64, 32);
      LArm.mirror = true;
      setRotation(LArm, -0.5235988F, 0F, 0F);
      LHand = new ModelRenderer(this, 0, 0);
      LHand.addBox(0F, 0F, 0F, 2, 2, 5);
      LHand.setRotationPoint(4.5F, 11.5F, 4F);
      LHand.setTextureSize(64, 32);
      LHand.mirror = true;
      setRotation(LHand, 0F, 0F, 0F);
      RHand = new ModelRenderer(this, 0, 0);
      RHand.addBox(0F, 0F, 0F, 2, 2, 5);
      RHand.setRotationPoint(-1.5F, 11.5F, 4F);
      RHand.setTextureSize(64, 32);
      RHand.mirror = true;
      setRotation(RHand, 0F, 0F, 0F);
  }
  

  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    HeadCrest.render(f5);
    Head.render(f5);
    AMouth.render(f5);
    BMouth.render(f5);
    Nostril.render(f5);
    RTheigh.render(f5);
    RAnkle.render(f5);
    RFoot.render(f5);
    LTheigh.render(f5);
    LAnkle.render(f5);
    LFoot.render(f5);
    ATail.render(f5);
    BTail.render(f5);
    Neck.render(f5);
    Body.render(f5);
    RArm.render(f5);
    LArm.render(f5);
    LHand.render(f5);
    RHand.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
  }

}
