// Date: 3/11/2013 8:31:32 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package MHF.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelStelactite extends ModelBase
{
  //fields
    ModelRenderer tip;
    ModelRenderer middle;
    ModelRenderer base;
  
  public ModelStelactite()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      tip = new ModelRenderer(this, 40, 0);
      tip.addBox(0F, 0F, 0F, 2, 7, 2);
      tip.setRotationPoint(-0.5F, 0F, -0.5F);
      tip.setTextureSize(64, 32);
      tip.mirror = true;
      setRotation(tip, 0F, 0F, 0F);
      middle = new ModelRenderer(this, 24, 0);
      middle.addBox(0F, 0F, 0F, 4, 9, 4);
      middle.setRotationPoint(-1F, 7F, -1F);
      middle.setTextureSize(64, 32);
      middle.mirror = true;
      setRotation(middle, 0F, 0F, 0F);
      base = new ModelRenderer(this, 0, 0);
      base.addBox(0F, 0F, 0F, 6, 8, 6);
      base.setRotationPoint(-2F, 16F, -2F);
      base.setTextureSize(64, 32);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    tip.render(f5);
    middle.render(f5);
    base.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void renderAll() {
	  tip.render(0.0625F);
	  middle.render(0.0625F);
	  base.render(0.0625F);
  }
}
